// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contributors.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createContributor = `-- name: CreateContributor :one
INSERT INTO Contributors (
    user_id,
    expertise_fields
) VALUES (
    $1,
    $2
)
RETURNING user_id, expertise_fields, created_at
`

type CreateContributorParams struct {
	UserID          uuid.UUID
	ExpertiseFields []string
}

func (q *Queries) CreateContributor(ctx context.Context, arg CreateContributorParams) (Contributor, error) {
	row := q.db.QueryRowContext(ctx, createContributor, arg.UserID, pq.Array(arg.ExpertiseFields))
	var i Contributor
	err := row.Scan(&i.UserID, pq.Array(&i.ExpertiseFields), &i.CreatedAt)
	return i, err
}

const deleteContributor = `-- name: DeleteContributor :exec
DELETE FROM Contributors
WHERE user_id = $1
`

func (q *Queries) DeleteContributor(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteContributor, userID)
	return err
}

const getContributorByUserId = `-- name: GetContributorByUserId :one
SELECT 
    user_id,
    expertise_fields,
    created_at
FROM Contributors
WHERE user_id = $1
`

func (q *Queries) GetContributorByUserId(ctx context.Context, userID uuid.UUID) (Contributor, error) {
	row := q.db.QueryRowContext(ctx, getContributorByUserId, userID)
	var i Contributor
	err := row.Scan(&i.UserID, pq.Array(&i.ExpertiseFields), &i.CreatedAt)
	return i, err
}

const listAllContributors = `-- name: ListAllContributors :many
SELECT 
    user_id,
    expertise_fields,
    created_at
FROM Contributors
`

func (q *Queries) ListAllContributors(ctx context.Context) ([]Contributor, error) {
	rows, err := q.db.QueryContext(ctx, listAllContributors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contributor
	for rows.Next() {
		var i Contributor
		if err := rows.Scan(&i.UserID, pq.Array(&i.ExpertiseFields), &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContributorsByExpertiseField = `-- name: SearchContributorsByExpertiseField :many
SELECT 
    user_id,
    expertise_fields,
    created_at
FROM Contributors
WHERE $1 = ANY(expertise_fields)
`

func (q *Queries) SearchContributorsByExpertiseField(ctx context.Context, expertiseFields []string) ([]Contributor, error) {
	rows, err := q.db.QueryContext(ctx, searchContributorsByExpertiseField, pq.Array(expertiseFields))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contributor
	for rows.Next() {
		var i Contributor
		if err := rows.Scan(&i.UserID, pq.Array(&i.ExpertiseFields), &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContributorExpertiseFields = `-- name: UpdateContributorExpertiseFields :exec
UPDATE Contributors
SET expertise_fields = $2
WHERE user_id = $1
`

type UpdateContributorExpertiseFieldsParams struct {
	UserID          uuid.UUID
	ExpertiseFields []string
}

func (q *Queries) UpdateContributorExpertiseFields(ctx context.Context, arg UpdateContributorExpertiseFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateContributorExpertiseFields, arg.UserID, pq.Array(arg.ExpertiseFields))
	return err
}
