// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: following.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFollow = `-- name: CreateFollow :exec
INSERT INTO following (follower_id, following_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateFollowParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) error {
	_, err := q.db.ExecContext(ctx, createFollow, arg.FollowerID, arg.FollowingID)
	return err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM following
WHERE follower_id = $1 AND following_id = $2
`

type DeleteFollowParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollow, arg.FollowerID, arg.FollowingID)
	return err
}

const getFeed = `-- name: GetFeed :many
SELECT posts.post_id, posts.title, posts.content, posts.slug, posts.user_id, posts.created_at, posts.updated_at
FROM posts
JOIN following ON posts.user_id = following.following_id
WHERE following.follower_id = $1
ORDER BY posts.created_at DESC
`

func (q *Queries) GetFeed(ctx context.Context, followerID uuid.UUID) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getFeed, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Content,
			&i.Slug,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowerList = `-- name: GetFollowerList :many
SELECT 
    follower_id
FROM following
WHERE following_id = $1
`

func (q *Queries) GetFollowerList(ctx context.Context, followingID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getFollowerList, followingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var follower_id uuid.UUID
		if err := rows.Scan(&follower_id); err != nil {
			return nil, err
		}
		items = append(items, follower_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingList = `-- name: GetFollowingList :many
SELECT 
    following_id
FROM following
WHERE follower_id = $1
`

func (q *Queries) GetFollowingList(ctx context.Context, followerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getFollowingList, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var following_id uuid.UUID
		if err := rows.Scan(&following_id); err != nil {
			return nil, err
		}
		items = append(items, following_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
