// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Appeal struct {
	AppealID       uuid.UUID
	AppealedBy     uuid.UUID
	TargetReportID uuid.UUID
	Reason         string
	Status         sql.NullString
	ReviewedAt     sql.NullTime
	Reviewedby     uuid.NullUUID
	CreatedAt      sql.NullTime
}

type Comment struct {
	CommentID       uuid.UUID
	PostID          uuid.UUID
	UserID          uuid.UUID
	ParentCommentID uuid.NullUUID
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Contributor struct {
	UserID          uuid.UUID
	ExpertiseFields []string
	CreatedAt       sql.NullTime
}

type ContributorApplication struct {
	ContriAppID       uuid.UUID
	UserID            uuid.UUID
	ExpertiseProofs   []string
	IdentityProof     string
	InitialSubmission string
	ReviewedBy        uuid.NullUUID
	Status            sql.NullString
	CreatedAt         sql.NullTime
	ReviewedAt        sql.NullTime
}

type Following struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

type Moderator struct {
	ModeratorID uuid.UUID
	Name        string
	Email       string
	Password    string
	Role        string
	CreatedBy   uuid.NullUUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Post struct {
	PostID    uuid.UUID
	Title     string
	Content   string
	Slug      string
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Report struct {
	ReportID        uuid.UUID
	ReportedBy      uuid.UUID
	TargetPostID    uuid.NullUUID
	TargetUserID    uuid.UUID
	TargetCommentID uuid.NullUUID
	Reason          string
	Status          sql.NullString
	ReviewedAt      sql.NullTime
	Reviewedby      uuid.NullUUID
	CreatedAt       sql.NullTime
	SuspendDays     sql.NullInt32
}

type SavedPost struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt sql.NullTime
}

type Upvote struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt sql.NullTime
}

type User struct {
	UserID         uuid.UUID
	Name           string
	Email          string
	Username       string
	Password       string
	SuspendedUntil sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
