// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID             uuid.UUID
	Name           string
	Email          string
	Password       string
	Role           sql.NullString
	SuspendedUntil sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
