// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID              uuid.UUID
	PostID          uuid.UUID
	UserID          uuid.UUID
	ParentCommentID uuid.NullUUID
	Content         string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Following struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
	FollowedAt sql.NullTime
}

type Post struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Slug      string
}

type Upvote struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Name           string
	Email          string
	Password       string
	Role           sql.NullString
	SuspendedUntil sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Username       string
}
