// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, 
    name, 
    email, 
    password, 
    role, 
    suspended_until) VALUES
    (
        $1, 
        $2, 
        $3, 
        $4, 
        $5, 
        $6
    )
    RETURNING id, name, email, role, suspended_until, created_at, updated_at
`

type CreateUserParams struct {
	ID             uuid.UUID
	Name           string
	Email          string
	Password       string
	Role           sql.NullString
	SuspendedUntil sql.NullTime
}

type CreateUserRow struct {
	ID             uuid.UUID
	Name           string
	Email          string
	Role           sql.NullString
	SuspendedUntil sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.SuspendedUntil,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.SuspendedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, 
    name, 
    email, 
    password, 
    role, 
    suspended_until, 
    created_at, 
    updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.SuspendedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
